version: "3.0"

services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    ports:
      - "9000:9090"
    volumes:
      - ./production/metrics/prometheus:/etc/prometheus
      - ./db-data/prometheus:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    user: root
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./production/metrics/grafana:/etc/grafana/provisioning/datasources
      - ./db-data/grafana:/var/lib/grafana

  broker-service:
    build:
      context: ./broker-service
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1